version: '3.8'

services:
  auth-service:
    build: 
      context: ./backend/auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://user:password@auth-db:5432/auth_db
      - JWT_SECRET=your-secret-key
    depends_on:
      - auth-db

  event-service:
    build:
      context: ./backend/event-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=mongodb://user:password@event-db:27017/event_db?authSource=admin
    depends_on:
      - event-db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - event-service

  auth-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth_db
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  event-db:
    image: mongo:6-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=event_db
    volumes:
      - event-db-data:/data/db
    ports:
      - "27017:27017"

volumes:
  auth-db-data:
  event-db-data: 