name: Send Email on Commit

on:
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          nodemailer_debug: 'true'      # Enable low-level SMTP debug output
          nodemailerlog: 'info'         # Show logs with 'info' level or higher
          server_address: smtp.mail.me.com
          server_port: 587
          secure: false                 # Usually false for port 587
          username: tunc_mustafa@icloud.com
          password: ${{ secrets.ICLOUD_APP_PASSWORD }}
          subject: "New Commit Notification"
          body: |
            A new commit has been pushed to the repository.
            Repository URL: https://github.com/<YOUR_USERNAME>/<YOUR_REPOSITORY>
            Commit: ${{ github.event.head_commit.id }}
            Commit Message: ${{ github.event.head_commit.message }}
          to: mustafatunc030600@gmail.com
          from: tunc_mustafa@icloud.com
